### ISSUE TITLE
Useless System.Net.Http

### ISSUE THREAD

**Issue by SharpDevSa** [Wagnerp/Windows-API-CodePack-NET#16]
What is the point to use System.Net.Http for this project? 
When you try to install this project from Nuget, it looks suspicious and asks you about this dependency that should be out of this library.

So, I think it is better to remove it from the project.

**Comment by Wagnerp** [comment]
> What is the point to use System.Net.Http for this project? When you try to install this project from Nuget, it looks suspicious and asks you about this dependency that should be out of this library.
> 
> So, I think it is better to remove it from the project.

Hi @SharpDevSa 

Is this a unused dependency, or is it in a file somewhere?

**Comment by SharpDevSa** [comment]
Yes, it is an unused package dependency that leads to the following dependencies in your project 
https://www.nuget.org/packages/WindowsAPICodePack/

So, if you remove it from 
`
[ExtendedLinguisticServices.csproj](https://github.com/Wagnerp/Windows-API-CodePack-NET/blob/3273220af3ebf8a2e5d4878bcb9766600fc21bc3/Source/Current/Windows%20API%20CodePack/Components/ExtendedLinguisticServices/ExtendedLinguisticServices.csproj#L61)

[Sensors.csproj](https://github.com/Wagnerp/Windows-API-CodePack-NET/blob/3273220af3ebf8a2e5d4878bcb9766600fc21bc3/Source/Current/Windows%20API%20CodePack/Components/Sensors/Sensors.csproj#L53)

[TestApp.csproj](https://github.com/Wagnerp/Windows-API-CodePack-NET/blob/3273220af3ebf8a2e5d4878bcb9766600fc21bc3/Source/Original/bugfixing/TestApp/TestApp/TestApp.csproj#L49)

[Core.csproj](https://github.com/Wagnerp/Windows-API-CodePack-NET/blob/3273220af3ebf8a2e5d4878bcb9766600fc21bc3/Source/Current/Windows%20API%20CodePack/Components/Core/Core.csproj#L53)
`

your project will not have dependencies on Nuget anymore and will look much better.

**Comment by Wagnerp** [comment]
Hi @SharpDevSa 

This has now been fixed in 8.0.5
