### ISSUE TITLE
`CommonFileDialogFilter` removes all `.` characters from the extension instead of just the first one

### ISSUE THREAD

**Issue by Crauzer** [Wagnerp/Windows-API-CodePack-NET#6]
**Describe the bug**
When creating a new `CommonFileDialogFilter` with an example extension `.wad.client`, the second `.` from the extension gets removed.
Some extensions can be composed with multiple dots.

**Expected behavior**
Only the first `.` character should be removed if it is specified as the first character of the extension.

 - Version: WindowsAPICodePackShell 7.0.3

**Comment by Wagnerp** [comment]
Hi @Crauzer 

Thanks for reporting, can you confirm if this is a issue with the current versions, or does it go back to the original 1.1 version too?

**Comment by Wagnerp** [comment]
Could there be something in here....

```cs
     public CommonFileDialogFilter(string? rawDisplayName, string extensionList)
            : this()
        {
            if (string.IsNullOrEmpty(extensionList))
            {
                throw new ArgumentNullException("extensionList");
            }

            this._rawDisplayName = rawDisplayName;

            // Parse string and create extension strings.
            // Format: "bat,cmd", or "bat;cmd", or "*.bat;*.cmd"
            // Can support leading "." or "*." - these will be stripped.
            string?[] rawExtensions = extensionList.Split(',', ';');
            foreach (string? extension in rawExtensions)
            {
                _extensions.Add(NormalizeExtension(extension));
            }
        }
```

**Comment by Wagnerp** [comment]
Hi @Crauzer 

Great news! I found a fix, it'll be in the next version. Sorry it took so long, ben busy on other projects.
