### ISSUE TITLE
System.ArgumentException: 'Value does not fall within the expected range.' when setting TabbedThumbnail and ThumbnailToolBars.

### ISSUE THREAD

**Issue by SunnyLeu** [Wagnerp/Windows-API-CodePack-NET#9]
**Describe the bug**
```cs
public Form_Main() {
    InitializeComponent();
    tabbedThumbnailManager = TaskbarManager.Instance.TabbedThumbnail;
    thumbnailToolBarManager = TaskbarManager.Instance.ThumbnailToolBars;
    #region //TabbedThumbnail
    tabbedThumbnail = new TabbedThumbnail(Handle, Handle);
    tabbedThumbnail.Title = this.Text;
    tabbedThumbnail.InvalidatePreview();
    tabbedThumbnail.SetWindowIcon(this.Icon!);
    tabbedThumbnailManager.AddThumbnailPreview(tabbedThumbnail);
    tabbedThumbnailManager.SetActiveTab(tabbedThumbnail);
    tabbedThumbnail.TabbedThumbnailClosed += TabbedThumbnail_TabbedThumbnailClosed;
    tabbedThumbnail.TabbedThumbnailActivated += TabbedThumbnail_TabbedThumbnailActivated;
    #endregion

    #region //ToolBarButton
    ToolBarButton_Previus = new ThumbnailToolBarButton(Icon.FromHandle(Properties.Resources.White_Previus.GetHicon()), "上一首");
    ToolBarButton_PlayPuase = new ThumbnailToolBarButton(Icon.FromHandle(Properties.Resources.Green_Play.GetHicon()), "播放");
    ToolBarButton_Next = new ThumbnailToolBarButton(Icon.FromHandle(Properties.Resources.White_Next.GetHicon()), "下一首");
    ToolBarButton_Previus.Click += ToolBarButton_Previus_Click;
    ToolBarButton_PlayPuase.Click += ToolBarButton_PlayPuase_Click;
    ToolBarButton_Next.Click += ToolBarButton_Next_Click;
    thumbnailToolBarManager.AddButtons(this.Handle, ToolBarButton_Previus, ToolBarButton_PlayPuase, ToolBarButton_Next);
    #endregion
    SetTabbedThumbnail("未開始播放");
    Form_Main_Resize(null, null);
}
[DllImport("User32.dll")]
public static extern int SetForegroundWindow(int hWnd);
private void TabbedThumbnail_TabbedThumbnailActivated(object? sender, TabbedThumbnailEventArgs e) {
    SetForegroundWindow(Handle.ToInt32());
    this.Activate();
    this.WindowState = FormWindowState.Maximized;
}
private void TabbedThumbnail_TabbedThumbnailClosed(object? sender, TabbedThumbnailClosedEventArgs e) {
    this.Close();
}
private void ToolBarButton_Next_Click(object? sender, ThumbnailButtonClickedEventArgs e) {
    NextButton.PerformClick();
}
private void ToolBarButton_PlayPuase_Click(object? sender, ThumbnailButtonClickedEventArgs e) {
    PlayPauseButton.PerformClick();
}
private void ToolBarButton_Previus_Click(object? sender, ThumbnailButtonClickedEventArgs e) {
    PreviusButton.PerformClick();
}
int WindowWidth;
int WindowHeight;
TabbedThumbnail tabbedThumbnail;
TabbedThumbnailManager tabbedThumbnailManager;
ThumbnailToolBarManager thumbnailToolBarManager;
ThumbnailToolBarButton ToolBarButton_Previus;
ThumbnailToolBarButton ToolBarButton_PlayPuase;
ThumbnailToolBarButton ToolBarButton_Next;
private void SetTabbedThumbnail(string text) {
    Bitmap bitmap1 = new Bitmap(WindowWidth, WindowHeight);
    using (Graphics bitmap1graphics = Graphics.FromImage(bitmap1)) {
        bitmap1graphics.Clear(Color.White);
        StringFormat stringFormat = new StringFormat();
        stringFormat.Alignment = StringAlignment.Center;
        stringFormat.LineAlignment = StringAlignment.Center;
        Font font = new Font("Microsoft JhengHei UI", (float)Math.Ceiling((float)(WindowWidth * 0.035)));
        SolidBrush brush = new SolidBrush(Color.Black);
        Rectangle rectangle = new Rectangle(10, 10, bitmap1.Width - 20, bitmap1.Height - 20);
        SolidBrush backgroundBrush = new SolidBrush(Color.White);
        bitmap1graphics.DrawString(text, font, brush, rectangle, stringFormat);
        bitmap1graphics.DrawRectangle(Pens.Black, Rectangle.Round(rectangle));
    }
    Bitmap bitmap2 = new Bitmap(WindowWidth, 100);
    using (Graphics bitmap2graphics = Graphics.FromImage(bitmap2)) {
        bitmap2graphics.Clear(Color.White);
        double p = (double)ProgressTrackBar.Value / (double)ProgressTrackBar.Maximum;
        bitmap2graphics.FillRectangle(Brushes.LimeGreen, 0, 0, (int)(bitmap2.Width * p), bitmap2.Height);
        bitmap2graphics.FillRectangle(Brushes.DarkGray, (int)(bitmap2.Width * p), 0, (int)(bitmap2.Width * (1 - p)), bitmap2.Height);
    }
    Bitmap mergedBitmap = new Bitmap(WindowWidth, WindowHeight + bitmap2.Height);
    using (Graphics mergedgraphics = Graphics.FromImage(mergedBitmap)) {
        mergedgraphics.DrawImage(bitmap1, new Point(0, 0));
        mergedgraphics.DrawImage(bitmap2, new Point(0, bitmap1.Height));
    }
    SetTabbedThumbnail(mergedBitmap);
}
private void SetTabbedThumbnail(Bitmap bitmap) {
    tabbedThumbnail.SetImage(bitmap);
}
```
this is the code I used to set TabbedThumbnail and ThumbnailToolBars, but this error appears:
```
System.ArgumentException: 'Value does not fall within the expected range.'
   於 Microsoft.WindowsAPICodePack.Taskbar.TabbedThumbnailNativeMethods.SetIconicThumbnail(IntPtr hwnd, IntPtr hBitmap)
   於 Microsoft.WindowsAPICodePack.Taskbar.TaskbarWindowManager.DispatchSendIconThumbnailMessage(Message& m, TaskbarWindow taskbarWindow)
   於 Microsoft.WindowsAPICodePack.Taskbar.TaskbarWindowManager.DispatchMessage(Message& m, TaskbarWindow taskbarWindow)
   於 Microsoft.WindowsAPICodePack.Taskbar.TabbedThumbnailProxyWindow.WndProc(Message& m)
   於 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam) 在 /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:行 369 中
   於 Interop.User32.DispatchMessageW(MSG& msg)
   於 System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData) 在 /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs:行 345 中
   於 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context) 在 /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:行 1117 中
   於 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context) 在 /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:行 981 中
   於 Music_Player.Program.Main() 在 D:\學校資料\C_File\Music_Player\Program.cs:行 59 中
```
I don't know the error reason, is this a bug? If not, how can I make it work?

**To Reproduce**
In the following video.
Imgur: [https://i.imgur.com/O4f3SM8.mp4](https://i.imgur.com/O4f3SM8.mp4)
or
Streamable: [https://streamable.com/4b5ins](https://streamable.com/4b5ins)

**Expected behavior**
Show a custom thumbnail that I set.

**Screenshots**
Already on above.

**Desktop (please complete the following information):**
 - OS: Windows 11 22621.1928

**Comment by SunnyLeu** [comment]
Is anyone here?

**Comment by Wagnerp** [comment]
Hi @SunnyLeu 

Sorry for the delay, I just picked it up, as I've been working on other projects. Would you mind attaching a sample project so that I can test?

**Comment by SunnyLeu** [comment]
> Hi @SunnyLeu
> 
> Sorry for the delay, I just picked it up, as I've been working on other projects. Would you mind attaching a sample project so that I can test?

Will......
I just tried the exactly same code all again, and it worked well done as before, but I didn't change any code related to Windows-API-CodePack, that's weird, the error just dissappeared......

**Comment by Wagnerp** [comment]
> > Hi @SunnyLeu
> > Sorry for the delay, I just picked it up, as I've been working on other projects. Would you mind attaching a sample project so that I can test?
> 
> Will...... I just tried the exactly same code all again, and it worked well done as before, but I didn't change any code related to Windows-API-CodePack, that's weird, the error just dissappeared......

Had a look at the GIF again, and it doesn't show any values in the stack trace?

**Comment by SunnyLeu** [comment]
> > > Hi @SunnyLeu
> > > Sorry for the delay, I just picked it up, as I've been working on other projects. Would you mind attaching a sample project so that I can test?
> > 
> > 
> > Will...... I just tried the exactly same code all again, and it worked well done as before, but I didn't change any code related to Windows-API-CodePack, that's weird, the error just dissappeared......
> 
> Had a look at the GIF again, and it doesn't show any values in the stack trace?

No, there's no any values.

**Comment by SunnyLeu** [comment]
I have another question related to thumbnails, when I setted a thumbnail and move the cursor on it to try to preview the window, it will always shows the loading circle.
![image](https://github.com/Wagnerp/Windows-API-CodePack-NET/assets/51817348/a7d7b6fc-408a-4a42-99d0-c0d549ddc421)
(The cursor position is at the word 'Pitch Perfect')
![image](https://github.com/Wagnerp/Windows-API-CodePack-NET/assets/51817348/1d7f5246-f157-4461-91ec-c7dbb4b43ee6)
And after about 15 seconds, the loading circle will stopped and shows the apps icon.

**Comment by SunnyLeu** [comment]
> Hi @SunnyLeu
> 
> Sorry for the delay, I just picked it up, as I've been working on other projects. Would you mind attaching a sample project so that I can test?

[Sample_WinFormsApp1.zip](https://github.com/Wagnerp/Windows-API-CodePack-NET/files/12396810/Sample_WinFormsApp1.zip)
Here's a sample app.

**Comment by Wagnerp** [comment]
> > Hi @SunnyLeu
> > Sorry for the delay, I just picked it up, as I've been working on other projects. Would you mind attaching a sample project so that I can test?
> 
> [Sample_WinFormsApp1.zip](https://github.com/Wagnerp/Windows-API-CodePack-NET/files/12396810/Sample_WinFormsApp1.zip) Here's a sample app.

I can't replicate the bug, is it triggered when you press something? As for the loading circle, I think it's a OS thing, as I've seen it in other apps (not using this library).

**Comment by SunnyLeu** [comment]
@Wagnerp 


> > Hi @SunnyLeu
> > Sorry for the delay, I just picked it up, as I've been working on other projects. Would you mind attaching a sample project so that I can test?
> 
> Will...... I just tried the exactly same code all again, and it worked well done as before, but I didn't change any code related to Windows-API-CodePack, that's weird, the error just dissappeared......

As I mentioned, the bug (System.ArgumentException) was disappeared for no reason, I don't know why, but it seems to be ok now.

**Comment by SunnyLeu** [comment]
@Wagnerp Ok, thanks for your help.
